name: kameleoon-test
services:
  app:
    build:
      dockerfile: ./Dockerfile
    image: thebluemitsu/kameleoon-trial-test:kameleoon-test
    ports:
      - "8000:8000"
    volumes:
        - ./:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: